from .frontend.ValuesFrontend import MUL, WIDTH, HEIGHT,SIZE,GAME_NAME

#NumOfPlayers VALUES
MIN_PLAYERS = 1
MAX_PLAYERS = 8
FONT_NAME_NUM_PLAYER = 'inkfree'
FONT_SIZE_NUM_PLAYER = 256
FONT_COLOR_NUM_PLAYER = (0,0,0)
COLOR_FILL_WINDOW = (0,0,0)
VG_IMG_PATH = './Game/frontend/img/'
LEFT_ARROW_COORDINATE_X = int(WIDTH/4)
LEFT_ARROW_COORDINATE_Y =int(HEIGHT/2)
RIGHT_ARROW_COORDINATE_X = int(WIDTH/4*3)
RIGHT_ARROW_COORDINATE_Y = int(HEIGHT/2)
OK_COORDINATE_X = int(WIDTH/2)
OK_COORDINATE_Y = int(HEIGHT/4*3)
TEXT_COORDINATE = (int(WIDTH/2),int(HEIGHT/2))
CHANGE_VALUE_PLAYERS = {'LEFT_ARROW_PRESSED':-1, 
                        'NOT_PRESSED':0,
                        'RIGHT_ARROW_PRESSED':1}
NOT_PRESSED ='NOT_PRESSED'
LEFT_ARROW_PRESSED = 'LEFT_ARROW_PRESSED'
RIGHT_ARROW_PRESSED = 'RIGHT_ARROW_PRESSED'

#PickName VALUES
SAVE_NAME_COORDINATE_X = int(WIDTH/4*3)
SAVE_NAME_COORDINATE_Y = int(HEIGHT/2)