from .frontend.ValuesFrontend import MUL, WIDTH, HEIGHT, SIZE, GAME_NAME, IMG_PATH, COLORS
from .backend.ValuesBacked import ROOMS_PER_FLOOR
from math import ceil
# NumOfPlayers VALUES
MIN_PLAYERS = 1
MAX_PLAYERS = 8
FONT_NAME_NUM_PLAYER = 'inkfree'
FONT_SIZE_NUM_PLAYER = 256
FONT_COLOR_NUM_PLAYER = COLORS.BLACK
COLOR_FILL_WINDOW = COLORS.BLACK
VG_IMG_PATH = './Game/frontend/img/'
LEFT_ARROW_COORDINATE_X = int(WIDTH/4)
LEFT_ARROW_COORDINATE_Y = int(HEIGHT/2)
RIGHT_ARROW_COORDINATE_X = int(WIDTH/4*3)
RIGHT_ARROW_COORDINATE_Y = int(HEIGHT/2)
OK_COORDINATE_X = int(WIDTH/2)
OK_COORDINATE_Y = int(HEIGHT/4*3)
OK_WIDTH = 200
OK_HEIGHT = 100
TEXT_COORDINATE = (int(WIDTH/2), int(HEIGHT/2))
CHANGE_VALUE_PLAYERS = {'LEFT_ARROW_PRESSED': -1,
                        'NOT_PRESSED': 0,
                        'RIGHT_ARROW_PRESSED': 1}
NOT_PRESSED = 'NOT_PRESSED'
LEFT_ARROW_PRESSED = 'LEFT_ARROW_PRESSED'
RIGHT_ARROW_PRESSED = 'RIGHT_ARROW_PRESSED'

# PickName VALUES
SAVE_NAME_COORDINATE_X = int(WIDTH/4*3)
SAVE_NAME_COORDINATE_Y = int(HEIGHT/2)

# PickLocation VALUES
FONT_NAME_LOCATION = 'inkfree'
FONT_SIZE_LOCATION = 32
FONT_COLOR_LOCATION = COLORS.BLACK
BACKGROUND_NAME_PLAYER_HEIGHT = 150
BACKGROUND_NAME_PLAYER_WIDTH = 300
BACKGROUND_NAME_PLAYER_X = int(WIDTH/2)
BACKGROUND_NAME_PLAYER_Y = int(BACKGROUND_NAME_PLAYER_HEIGHT/2)
STATIC_TEXT_COORDINATE_X = BACKGROUND_NAME_PLAYER_X
STATIC_TEXT_COORDINATE_Y = BACKGROUND_NAME_PLAYER_Y-int(BACKGROUND_NAME_PLAYER_HEIGHT/4)
DYNAMIC_TEXT_COORDINATE_X = BACKGROUND_NAME_PLAYER_X
DYNAMIC_TEXT_COORDINATE_Y = BACKGROUND_NAME_PLAYER_Y+int(BACKGROUND_NAME_PLAYER_HEIGHT/4)
WIDTH_RECTANGLE_PICK = int(WIDTH/3)
BORDER_RECT_TO_PICK = 5
BORDER_RECT_PICKED = 10


# GetDataInput Values
INPUT_DATA_WIDTH = 700
INPUT_DATA_HEIGHT = 525


#GameHotel Values
WIDTH_GAME_BACKGROUND = WIDTH
HEIGHT_GAME_BACKGROUND = HEIGHT
BACKGROUND_GAME_X = 0
BACKGROUND_GAME_Y = 0
WIDTH_MENUBAR_BACKGROUND = WIDTH
HEIGHT_MENUBAR_BACKGROUND = 120
BACKGROUND_MENUBAR_X= 0
BACKGROUND_MENUBAR_Y= 0

GAME_FONT_NAME = 'inkfree'
GAME_FONT_SIZE = 45
GAME_FONT_COLOR = COLORS.BLACK

GAME_NAME_COORDINATE = (BACKGROUND_MENUBAR_X+ 10,int(BACKGROUND_MENUBAR_Y + HEIGHT_MENUBAR_BACKGROUND/4 - GAME_FONT_SIZE/2))
GAME_MONEY_COORDINATE = (BACKGROUND_MENUBAR_X+ 10,int(BACKGROUND_MENUBAR_Y + HEIGHT_MENUBAR_BACKGROUND - HEIGHT_MENUBAR_BACKGROUND/4 - GAME_FONT_SIZE/2))

NEXT_LINE_ROOM = ceil(ROOMS_PER_FLOOR/2)

WIDTH_ROOM = ceil(WIDTH / NEXT_LINE_ROOM)
HEIGHT_ROOM = WIDTH_ROOM

UP_ROOM_Y = 0+HEIGHT_MENUBAR_BACKGROUND+HEIGHT_ROOM/2
DOWN_ROOM_Y = HEIGHT-HEIGHT_ROOM/2

GAME_MENUBAR_ICON_WIDTH = 3/4 * HEIGHT_MENUBAR_BACKGROUND
GAME_MENUBAR_ICON_HEIGHT = GAME_MENUBAR_ICON_WIDTH
GAME_MENUBAR_ICON_Y = BACKGROUND_MENUBAR_Y + HEIGHT_MENUBAR_BACKGROUND/2

OFFSET_FLOOR_CONTROLLER=((WIDTH/2)/5*4)

PREV_FLOOR_X =OFFSET_FLOOR_CONTROLLER-GAME_MENUBAR_ICON_WIDTH
PREV_FLOOR_Y = GAME_MENUBAR_ICON_Y
PREV_FLOOR_WIDTH = GAME_MENUBAR_ICON_WIDTH
PREV_FLOOR_HEIGHT = GAME_MENUBAR_ICON_HEIGHT

NEXT_FLOOR_X = OFFSET_FLOOR_CONTROLLER+GAME_MENUBAR_ICON_WIDTH
NEXT_FLOOR_Y = GAME_MENUBAR_ICON_Y
NEXT_FLOOR_WIDTH = GAME_MENUBAR_ICON_WIDTH
NEXT_FLOOR_HEIGHT = GAME_MENUBAR_ICON_HEIGHT

FLOOR_TEXT_X = OFFSET_FLOOR_CONTROLLER
FLOOR_TEXT_Y = BACKGROUND_MENUBAR_Y + HEIGHT_MENUBAR_BACKGROUND/2
FLOOR_TEXT_COORDINATE = (FLOOR_TEXT_X,FLOOR_TEXT_Y)

BOX_NUM_PRESS = 5
OFFSET = GAME_MENUBAR_ICON_WIDTH/BOX_NUM_PRESS
START_POS_X = WIDTH_MENUBAR_BACKGROUND - (BOX_NUM_PRESS+1)*GAME_MENUBAR_ICON_WIDTH

ADD_FLOOR_HEIGHT = GAME_MENUBAR_ICON_HEIGHT
ADD_FLOOR_WIDTH = ADD_FLOOR_HEIGHT
ADD_FLOOR_X = START_POS_X
ADD_FLOOR_Y = BACKGROUND_MENUBAR_Y +  GAME_MENUBAR_ICON_Y

BUY_ROOM_HEIGHT = GAME_MENUBAR_ICON_HEIGHT
BUY_ROOM_WIDTH = BUY_ROOM_HEIGHT
BUY_ROOM_X = ADD_FLOOR_X+GAME_MENUBAR_ICON_WIDTH+OFFSET
BUY_ROOM_Y = BACKGROUND_MENUBAR_Y +  GAME_MENUBAR_ICON_Y

UPGRADE_ROOM_HEIGHT = GAME_MENUBAR_ICON_HEIGHT
UPGRADE_ROOM_WIDTH = UPGRADE_ROOM_HEIGHT
UPGRADE_ROOM_X = BUY_ROOM_X+GAME_MENUBAR_ICON_WIDTH+OFFSET
UPGRADE_ROOM_Y = BACKGROUND_MENUBAR_Y +  GAME_MENUBAR_ICON_Y

DOWNGRADE_ROOM_HEIGHT = GAME_MENUBAR_ICON_HEIGHT
DOWNGRADE_ROOM_WIDTH = DOWNGRADE_ROOM_HEIGHT
DOWNGRADE_ROOM_X = UPGRADE_ROOM_X+GAME_MENUBAR_ICON_WIDTH+OFFSET
DOWNGRADE_ROOM_Y = BACKGROUND_MENUBAR_Y +  GAME_MENUBAR_ICON_Y

SWITCH_TO_BANK_HEIGHT = GAME_MENUBAR_ICON_HEIGHT
SWITCH_TO_BANK_WIDTH = SWITCH_TO_BANK_HEIGHT
SWITCH_TO_BANK_X = DOWNGRADE_ROOM_X+GAME_MENUBAR_ICON_WIDTH+OFFSET
SWITCH_TO_BANK_Y = BACKGROUND_MENUBAR_Y +  GAME_MENUBAR_ICON_Y
