#GLOBAL VALUES
MUL = 1.9
WIDTH = int(720*MUL)
HEIGHT = int(405*MUL)
SIZE = (WIDTH,HEIGHT)
GAME_NAME = "HOTEL-STAR"
#BUTTON values
IMG_PATH = './Game/frontend/img/'
#INPUT VALUES
LENGTH_INPUT = 500
HEIGHT_INPUT = 50

class COLORS:
    BLACK = (0,0,0)