# ROOM VALUES
ROOM_LEVEL_INITIAL_VALUE = 0
EMPLOYEE_LIST_NUM = [0, 0.25, 0.5, 0.75, 1]
VIP_TRUE = True
VIP_FALSE = False

# HOTEL VALUES
ROOMS_PER_FLOOR = 10
FLOOR_COST_INITIAL = [0, 0, 0, 0, 0]

# PLAYER VALUES
INITIAL_MONEY = 75000
INITIAL_DEBT = 0

# LOCATION VALUES
INITIAL_NUMBER_OF_CUSTOMERS = 100
UP_BAND = 1.5
DW_BAND = 0.8
LOCATION_VIP_PTR = {'CENTER': 0.2, 'SUBURB': 0.5, 'DOWNTOWN': 0.8}
INITIAL_TURN = 0

# BANK VALUES
DIVIDER = 0.1
EARN_LIST = []
LAST_FOUR_QUARTERS = 4
